# Generated by Django 3.2.4 on 2021-07-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=100)),
                ('beer_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('type', models.CharField(max_length=15)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Drinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='drinking date')),
                ('served', models.CharField(choices=[('C', 'Can'), ('B', 'Bottle'), ('D', 'Draft'), ('G', 'Growler')], default='C', max_length=1)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
