# Generated by Django 3.2.4 on 2021-07-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hops',
            new_name='Hop',
        ),
        migrations.CreateModel(
            name='Drinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='drinking date')),
                ('served', models.CharField(choices=[('C', 'Can'), ('B', 'Bottle'), ('D', 'Draft'), ('G', 'Growler')], default='C', max_length=1)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
