# Generated by Django 3.2.4 on 2021-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210708_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(to='main_app.Hop'),
        ),
    ]
