# Generated by Django 3.2.4 on 2021-07-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_where'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hop',
        ),
    ]
