# Generated by Django 3.2.4 on 2021-07-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210712_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hop',
        ),
    ]
