# Generated by Django 3.2.4 on 2021-07-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_hop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hop',
        ),
        migrations.DeleteModel(
            name='Where',
        ),
    ]
