# Generated by Django 3.2.4 on 2021-07-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_hop_where'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='hop',
            name='alpha_acid',
            field=models.DecimalField(decimal_places=2, default='10.60', max_digits=5),
        ),
        migrations.AddField(
            model_name='hop',
            name='characteristics',
            field=models.CharField(default='hoppy', max_length=60),
        ),
        migrations.AddField(
            model_name='hop',
            name='color',
            field=models.CharField(default='Green', max_length=5),
        ),
        migrations.AddField(
            model_name='hop',
            name='name',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
