# Generated by Django 3.2.4 on 2021-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210714_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hop',
            name='color',
        ),
        migrations.AddField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(to='main_app.Hop'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='alpha_acid',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='hop',
            name='characteristics',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='hop',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
