# Generated by Django 3.2.4 on 2021-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210714_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='characteristics',
            field=models.CharField(default='', max_length=170),
        ),
    ]
