# Generated by Django 3.2.5 on 2021-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_hop_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='where',
            name='indoors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='where',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='where',
            name='restaurant',
            field=models.BooleanField(default=True),
        ),
    ]
