# Generated by Django 3.2.5 on 2021-07-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210714_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='where',
            name='indoors',
        ),
        migrations.AlterField(
            model_name='where',
            name='restaurant',
            field=models.CharField(default='', max_length=35),
        ),
    ]
