# Generated by Django 3.2.5 on 2021-07-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210714_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
